const PATH = {
  root: "/",
  admin: "/admin",
  signIn: "/dang-nhap",
  event: "/su-kien",
  free_account: "/tai-khoan-mien-phi",
  moderator: "/moderator",
  account_management: "/moderator/quan-ly-tai-khoan",
  user_debt: "/moderator/no-nguoi-dung",
  transaction_history_manager: "/moderator/lich-su-giao-dich",
  approval_topup_request: "/moderator/duyet-yeu-cau-nap-tien",
  waiting_topup_request: "/moderator/duyet-yeu-cau-nap-tien/cho-duyet",
  topup_request_history: "/moderator/duyet-yeu-cau-nap-tien/lich-su",
  send_notification: "/moderator/gui-thong-bao",
  view_feedback: "/moderator/xem-gop-y",
  played_time: "/moderator/thoi-gian-choi",
  free_account_management: "/moderator/tai-khoan-mien-phi",
  account: "/account",
  account_info: "/account/thong-tin-tai-khoan",
  transaction_history: "/account/lich-su-giao-dich",
  debt_detail: "/account/chi-tiet-so-no",
  change_password: "/account/doi-mat-khau",
  feedback: "/account/gop-y",
  moderator_account_management: "/admin/quan-ly-tai-khoan",
  voucher_management: "/admin/quan-ly-voucher",
  ht_road_event: "/admin/su-kien-ht-road",
  ht_road_event_ongoing: "/admin/su-kien-ht-road/dang-dien-ra",
  ht_road_event_history: "/admin/su-kien-ht-road/lich-su",
};

export default PATH;
